### ISSUE TITLE
Issues with yarn with --install.modules-folder option

### ISSUE THREAD

**Issue by gevorgmansuryan** [kesne/acorn-dynamic-import#12]
# current behavior

yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
error An unexpected error occurred: "ENOENT: no such file or directory, lstat '/ginosi/incubator/yarn/backoffice/node_modules/acorn-dynamic-import/node_modules/acorn'".
info If you think this is a bug, please open a bug report with the information provided in "/ginosi/backoffice/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

# steps to reproduce.

try `yarn install --force` twice with

`.yarnrc` file with contents
`--install.modules-folder "../incubator/yarn/backoffice/node_modules"`

# expected behavior
Install should work

OS: Ubuntu 16.10
Node: 8.9.4
Yarn: 1.3.2

**Comment by kesne** [comment]
Sounds like a yarn bug.
