### ISSUE TITLE
Extending walk this way steers people wrong

### ISSUE THREAD

**Issue by marijnh** [kesne/acorn-dynamic-import#17]
By returning a 'full' instance of the `acorn-walk` API, the library kind of suggests that the methods on that interface have been extended to support the new node type... but by default, if you don't pass them an explicit base walker, they'll use the base object that they closed over, which is the old, non-extended one. See https://github.com/acornjs/acorn/issues/746.

I think a reasonable solution would be to create a module that just extends the base walker object, i.e. takes such an object and returns an extended version. That both works better with ES modules (less dynamic munging of exported interfaces) and steers people towards using the code correctly.

That'd be a breaking change, so if bumping the major version number is an issue, we could leave the old interface around and implement this in a separate file.

Would be happy to create a PR if this sounds reasonable.

**Comment by kesne** [comment]
I'm not sure I understand the issue, can you demonstrate what this would end up looking like in code?

**Comment by kesne** [comment]
Closing this. This is going to be added to Acorn, and can be filed there if it's still an issue.
