### ISSUE TITLE
upgrade dependencies now acorn@7 is out?

### ISSUE THREAD

**Issue by zawsx** [kesne/acorn-dynamic-import#22]
Guess that the stated dependency on acorn@6 is not satisfied by acorn@7 ?

**Comment by archmoj** [comment]
+1

**Comment by adrianheine** [comment]
acorn supports dynamic import since 6.2, so you don't need this plugin anymore.

**Comment by zawsx** [comment]
Thanks but it's not me that needs it, it's a sub-module in package.json apparently. Now I know it's not needed, I will ignore the warning - thanks :)
