### ISSUE TITLE
whitespace between `import` and `(`.

### ISSUE THREAD

**Issue by jdalton** [kesne/acorn-dynamic-import#6]
I noticed whitespace in `import      (a)` (between the `import` and `(`) isn't allowed, but I believe it should be allowed.

The [line here](https://github.com/kesne/acorn-dynamic-import/blob/bbde06efe095935575ec6454223d0a1d3b4e748e/src/inject.js#L19), which looks at input position, should be a token lookahead [similar to Babylon](https://github.com/babel/babylon/blob/aa78011666b890772c9be8936f29815ddc4c0af0/src/parser/statement.js#L109).

**Comment by kesne** [comment]
Thanks for making this issue! When I wrote this plugin it didn't seem like acorn had a mechanism to perform a lookahead. It might just be that I'm not familiar enough with acorn though.

**Comment by jdalton** [comment]
Acorn doesn't have a helper (that I know of) but I have a neat trick to do it (using the flyweight pattern). See [here](https://github.com/standard-things/esm/blob/19add243465e4131d4d89508a85f55fb18bcb769/src/utils.js#L186-L191) (it's applied [here](https://github.com/standard-things/esm/blob/19add243465e4131d4d89508a85f55fb18bcb769/src/acorn-extensions/dynamic-import.js#L34)).

**Comment by marijnh** [comment]
I think I fixed this in https://github.com/kesne/acorn-dynamic-import/pull/14
